### ISSUE TITLE
Leros behavior on branch instruction

### ISSUE THREAD

**Issue by SyedAnasAlam** [leros-dev/leros#11]
Below is a small test program to test branch instructions. Leros should branch to ```A``` load 0 into the accumulator and make a system call with argument ```0```. This is also what Leros does, and it finishes the program with ```0``` in the accumulator. However when taking a look at the simulation waveform Leros also loads the instruction ``` loadi 0xFF (0x21FF)```, but it does not seem to execute the instruction. Is this the desired behavior of Leros? 
```
start:
    loadi 1       // 0x2101
    brnz A        // 0xA003
    loadi 0xFF    // 0x21FF
    br start      // 0x8FFD


A:
    loadi 0       // 0x2100
    scall 0       // 0xFF00
```
Waveform:
![unnamed](https://github.com/user-attachments/assets/5e90ed4a-6a38-43c2-89ea-9e151b923f5a)

To reproduce: 
Add above test program under ```asm/test/``` 
Run  ```LerosTest``` and open waveform generated waveform

**Comment by schoeberl** [comment]
As ```pcNext``` points into the instruction memory, it prefetches the next instruction. The combinational ```pcNext``` is used, as the ROM has an input register for the address. When there is a branch, the prefetched instruction is just ignored when the branch is taken.
